local addonName, TEJ = ...

TEJ.Routes = {
    {
        id = "loch-modan-ironforge-airport-farms",
        name = "Loch Modan to Ironforge Airport / Farms",
        category = "Hidden Areas",
        continent = "eastern-kingdoms",
        difficulty = "easy",
        mapID = 1432,
        description = "A cross-zone mountain route from Loch Modan into Dun Morogh toward the Ironforge Airport and farms.",
        waypoints = {
            {
                mapID = 1432,
                x = 0.1957,
                y = 0.1521,
                label = "Starting mountain latch",
                note = "Continue jumping at the mountain until you latch on, and are able to jump once more up the mountain. This step can be tricky and take awhile.",
            },
            {
                mapID = 1432,
                x = 0.1904,
                y = 0.1420,
                label = "Hug left up the mountain",
                note = "Be sure to continue up the mountain, hugging left.",
            },
            {
                mapID = 1432,
                x = 0.1833,
                y = 0.1456,
                label = "Past the first tree",
                note = "Go past the tree and its textures, until you reach the next tree.",
            },
            {
                mapID = 1432,
                x = 0.1744,
                y = 0.1441,
                label = "Past the next trees",
                note = "Continue up the mountain, going past the next two trees.",
            },
            {
                mapID = 1432,
                x = 0.1646,
                y = 0.1275,
                label = "Left past blocking tree",
                note = "After passing the second tree, hang a left and jump past the tree that is in the way of the path.",
            },
            {
                mapID = 1432,
                x = 0.1514,
                y = 0.1367,
                label = "Keep left and climb",
                note = "Once past the tree, continue to hang a left and go up the mountain.",
            },
            {
                mapID = 1432,
                x = 0.1444,
                y = 0.1547,
                label = "Right up steep hill",
                note = "Be sure to hang a right here, going up the steep hill. You should be able to run directly up the hill.",
            },
            {
                mapID = 1432,
                x = 0.1268,
                y = 0.1514,
                label = "Right and climb again",
                note = "Once down the hill, be sure to go right and up the hill again. You should be able to run up the hill.",
            },
            {
                mapID = 1432,
                x = 0.1257,
                y = 0.1067,
                label = "Left side descent",
                note = "Once at the top of the hill, go back down the hill staying on the left hand side of the mountain.",
            },
            {
                mapID = 1426,
                x = 0.8526,
                y = 0.2179,
                label = "Dun Morogh snow line",
                note = "Once down the hill, keep walking forward and take a right. When you reach this waypoint you should be in Dun Morogh now. Keep following the snow to the next waypoint.",
            },
            {
                mapID = 1426,
                x = 0.7958,
                y = 0.2107,
                label = "Slight right to snowy hill",
                note = "At this waypoint, be sure to take a slight right toward the fully snowy looking hill.",
            },
            {
                mapID = 1426,
                x = 0.7691,
                y = 0.1766,
                label = "Dead tree ahead",
                note = "Now at the top of the snowy hill, head toward the dead tree right in front of you.",
            },
            {
                mapID = 1426,
                x = 0.7507,
                y = 0.1501,
                label = "Sharp left at dead tree",
                note = "Once at the dead tree, take a sharp left. Continue forward to the next waypoint.",
            },
            {
                mapID = 1426,
                x = 0.7225,
                y = 0.1570,
                label = "Sharp left again",
                note = "At this waypoint, take a sharp left once more.",
            },
            {
                mapID = 1426,
                x = 0.7215,
                y = 0.1789,
                label = "Ironforge Airport / Farms",
                note = "Congratulations! You should now see buildings and are free to explore the airport as you please!",
            },
        },
    },
    {
        id = "tanaris-caverns-of-time-video-guide",
        name = "Tanaris to Caverns of Time",
        category = "Hidden Areas",
        continent = "kalimdor",
        difficulty = "advanced",
        mapID = 1446,
        description = "Video-derived route for entering the closed Caverns of Time area in Classic. Source: SweetJohnnyCage, Caverns of Time Access Guide + Exploration, https://www.youtube.com/watch?v=V5xR9SCoP-0. Only the start coordinate is exact from the video transcript; later waypoints are approximate guide markers for refinement with GPS waypoints.",
        waypoints = {
            {
                mapID = 1446,
                x = 0.6756,
                y = 0.5600,
                label = "Start at Caverns ridge",
                note = "Go to Tanaris 67,56 on the southern side of the Caverns of Time mountain range. This is the exact coordinate called out in the video.",
            },
            {
                mapID = 1446,
                x = 0.6768,
                y = 0.5538,
                label = "Climb toward the ruins",
                note = "Run up the hill toward the ruin-looking structure. Expect a small amount of wall walking before the ruin approach.",
            },
            {
                mapID = 1446,
                x = 0.6810,
                y = 0.5500,
                label = "Visible edge attempt",
                note = "Try to catch on the visible edge of the ruin and walk up. The video notes this may not work reliably in Classic.",
            },
            {
                mapID = 1446,
                x = 0.6832,
                y = 0.5480,
                label = "Fear boost position",
                note = "If the wall-walk is too steep, duel a helper with Fear or similar loss-of-control ability, such as priest, warlock, or warrior. Have them fear you here to push you up onto the higher area.",
            },
            {
                mapID = 1446,
                x = 0.6860,
                y = 0.5440,
                label = "Follow the mountain",
                note = "Once above the ruin, follow the mountain route upward toward the ridge.",
            },
            {
                mapID = 1446,
                x = 0.6895,
                y = 0.5390,
                label = "Walk the ledge",
                note = "Walk along the ledge. If it feels risky, toggle walk with numpad slash and edge around carefully.",
            },
            {
                mapID = 1446,
                x = 0.6950,
                y = 0.5350,
                label = "Tower overlook",
                note = "Move toward the tower overlook that is visible from the Caverns of Time area in Tanaris.",
            },
            {
                mapID = 1446,
                x = 0.7000,
                y = 0.5310,
                label = "Black box jump",
                note = "Jump off near the black box/object shown in the video and aim to land on the brown mountain surface below.",
            },
            {
                mapID = 1446,
                x = 0.7035,
                y = 0.5275,
                label = "Heal before next jump",
                note = "Heal to full before continuing. Eat, bandage, or use healing spells because the next drop is large.",
            },
            {
                mapID = 1446,
                x = 0.7070,
                y = 0.5225,
                label = "Purple window jump",
                note = "Head toward the purple window. Run into it and jump so you glide down toward the right-hand ledge.",
            },
            {
                mapID = 1446,
                x = 0.7115,
                y = 0.5180,
                label = "Behind the door",
                note = "After landing on the ledge, jump down behind the door to enter the Caverns of Time area.",
            },
            {
                mapID = 1446,
                x = 0.7140,
                y = 0.5140,
                label = "Caverns of Time",
                note = "You should be inside the closed Caverns of Time area. The video notes the portals do not function; hearth out or die to leave.",
            },
        },
    },
}
