local addonName, TEJ = ...

TEJ.Routes = {
    {
        id = "loch-modan-ironforge-airport-farms",
        name = "Loch Modan to Ironforge Airport / Farms",
        category = "Hidden Areas",
        continent = "eastern-kingdoms",
        difficulty = "easy",
        mapID = 1432,
        description = "A cross-zone mountain route from Loch Modan into Dun Morogh toward the Ironforge Airport and farms.",
        waypoints = {
            {
                mapID = 1432,
                x = 0.1957,
                y = 0.1521,
                label = "Starting mountain latch",
                note = "Continue jumping at the mountain until you latch on, and are able to jump once more up the mountain. This step can be tricky and take awhile.",
            },
            {
                mapID = 1432,
                x = 0.1904,
                y = 0.1420,
                label = "Hug left up the mountain",
                note = "Be sure to continue up the mountain, hugging left.",
            },
            {
                mapID = 1432,
                x = 0.1833,
                y = 0.1456,
                label = "Past the first tree",
                note = "Go past the tree and its textures, until you reach the next tree.",
            },
            {
                mapID = 1432,
                x = 0.1744,
                y = 0.1441,
                label = "Past the next trees",
                note = "Continue up the mountain, going past the next two trees.",
            },
            {
                mapID = 1432,
                x = 0.1646,
                y = 0.1275,
                label = "Left past blocking tree",
                note = "After passing the second tree, hang a left and jump past the tree that is in the way of the path.",
            },
            {
                mapID = 1432,
                x = 0.1514,
                y = 0.1367,
                label = "Keep left and climb",
                note = "Once past the tree, continue to hang a left and go up the mountain.",
            },
            {
                mapID = 1432,
                x = 0.1444,
                y = 0.1547,
                label = "Right up steep hill",
                note = "Be sure to hang a right here, going up the steep hill. You should be able to run directly up the hill.",
            },
            {
                mapID = 1432,
                x = 0.1268,
                y = 0.1514,
                label = "Right and climb again",
                note = "Once down the hill, be sure to go right and up the hill again. You should be able to run up the hill.",
            },
            {
                mapID = 1432,
                x = 0.1257,
                y = 0.1067,
                label = "Left side descent",
                note = "Once at the top of the hill, go back down the hill staying on the left hand side of the mountain.",
            },
            {
                mapID = 1426,
                x = 0.8526,
                y = 0.2179,
                label = "Dun Morogh snow line",
                note = "Once down the hill, keep walking forward and take a right. When you reach this waypoint you should be in Dun Morogh now. Keep following the snow to the next waypoint.",
            },
            {
                mapID = 1426,
                x = 0.7958,
                y = 0.2107,
                label = "Slight right to snowy hill",
                note = "At this waypoint, be sure to take a slight right toward the fully snowy looking hill.",
            },
            {
                mapID = 1426,
                x = 0.7691,
                y = 0.1766,
                label = "Dead tree ahead",
                note = "Now at the top of the snowy hill, head toward the dead tree right in front of you.",
            },
            {
                mapID = 1426,
                x = 0.7507,
                y = 0.1501,
                label = "Sharp left at dead tree",
                note = "Once at the dead tree, take a sharp left. Continue forward to the next waypoint.",
            },
            {
                mapID = 1426,
                x = 0.7225,
                y = 0.1570,
                label = "Sharp left again",
                note = "At this waypoint, take a sharp left once more.",
            },
            {
                mapID = 1426,
                x = 0.7215,
                y = 0.1789,
                label = "Ironforge Airport / Farms",
                note = "Congratulations! You should now see buildings and are free to explore the airport as you please!",
            },
        },
    },
    {
        id = "tanaris-caverns-of-time-video-guide",
        name = "Tanaris to Caverns of Time",
        category = "Hidden Areas",
        continent = "kalimdor",
        difficulty = "advanced",
        mapID = 1446,
        description = "Video-derived route for entering the closed Caverns of Time area in Classic. Source: SweetJohnnyCage, Caverns of Time Access Guide + Exploration, https://www.youtube.com/watch?v=V5xR9SCoP-0. Only the start coordinate is exact from the video transcript; later waypoints are approximate guide markers for refinement with GPS waypoints.",
        waypoints = {
            {
                mapID = 1446,
                x = 0.6756,
                y = 0.5600,
                label = "Start at Caverns ridge",
                note = "Go to Tanaris 67,56 on the southern side of the Caverns of Time mountain range. This is the exact coordinate called out in the video.",
            },
            {
                mapID = 1446,
                x = 0.6768,
                y = 0.5538,
                label = "Climb toward the ruins",
                note = "Run up the hill toward the ruin-looking structure. Expect a small amount of wall walking before the ruin approach.",
            },
            {
                mapID = 1446,
                x = 0.6810,
                y = 0.5500,
                label = "Visible edge attempt",
                note = "Try to catch on the visible edge of the ruin and walk up. The video notes this may not work reliably in Classic.",
            },
            {
                mapID = 1446,
                x = 0.6832,
                y = 0.5480,
                label = "Fear boost position",
                note = "If the wall-walk is too steep, duel a helper with Fear or similar loss-of-control ability, such as priest, warlock, or warrior. Have them fear you here to push you up onto the higher area.",
            },
            {
                mapID = 1446,
                x = 0.6860,
                y = 0.5440,
                label = "Follow the mountain",
                note = "Once above the ruin, follow the mountain route upward toward the ridge.",
            },
            {
                mapID = 1446,
                x = 0.6895,
                y = 0.5390,
                label = "Walk the ledge",
                note = "Walk along the ledge. If it feels risky, toggle walk with numpad slash and edge around carefully.",
            },
            {
                mapID = 1446,
                x = 0.6950,
                y = 0.5350,
                label = "Tower overlook",
                note = "Move toward the tower overlook that is visible from the Caverns of Time area in Tanaris.",
            },
            {
                mapID = 1446,
                x = 0.7000,
                y = 0.5310,
                label = "Black box jump",
                note = "Jump off near the black box/object shown in the video and aim to land on the brown mountain surface below.",
            },
            {
                mapID = 1446,
                x = 0.7035,
                y = 0.5275,
                label = "Heal before next jump",
                note = "Heal to full before continuing. Eat, bandage, or use healing spells because the next drop is large.",
            },
            {
                mapID = 1446,
                x = 0.7070,
                y = 0.5225,
                label = "Purple window jump",
                note = "Head toward the purple window. Run into it and jump so you glide down toward the right-hand ledge.",
            },
            {
                mapID = 1446,
                x = 0.7115,
                y = 0.5180,
                label = "Behind the door",
                note = "After landing on the ledge, jump down behind the door to enter the Caverns of Time area.",
            },
            {
                mapID = 1446,
                x = 0.7140,
                y = 0.5140,
                label = "Caverns of Time",
                note = "You should be inside the closed Caverns of Time area. The video notes the portals do not function; hearth out or die to leave.",
            },
        },
    },
    {
        id = "orgrimmar-under-city-video-guide",
        name = "Under Orgrimmar",
        category = "Hidden Areas",
        continent = "kalimdor",
        difficulty = "advanced",
        mapID = 1454,
        description = "Video-derived route for reaching the underside of Orgrimmar from the north side of Valley of Honor. Source: Cal, classic glitches video, https://www.youtube.com/watch?v=u6VmixOH6rg. Waypoints are approximate guide markers and should be refined with GPS captures.",
        waypoints = {
            {
                mapID = 1454,
                x = 0.7920,
                y = 0.3020,
                label = "North Valley of Honor",
                note = "Start at the north point of Orgrimmar in Valley of Honor. The video suggests a mount is likely required for the longer jumps.",
            },
            {
                mapID = 1454,
                x = 0.7980,
                y = 0.2860,
                label = "First rock climb",
                note = "Jump onto the rock section near the north wall. Keep adjusting until you can stand high enough to continue.",
            },
            {
                mapID = 1454,
                x = 0.8040,
                y = 0.2750,
                label = "Twig run-up",
                note = "Run up the twig or branch-like edge, then turn around and mount up for the longer jump.",
            },
            {
                mapID = 1454,
                x = 0.8120,
                y = 0.2820,
                label = "Mounted jump to rocks",
                note = "Use the mounted jump to reach the next rock section. Slow Fall was tried in the video but was not successful.",
            },
            {
                mapID = 1454,
                x = 0.8210,
                y = 0.2920,
                label = "Second stick jump",
                note = "Move around to the next stick-like edge. Mount again and line up the jump toward the building.",
            },
            {
                mapID = 1454,
                x = 0.8300,
                y = 0.3020,
                label = "Building landing",
                note = "Land on the building. From here you should be able to see areas beyond the gate that are not normally shown.",
            },
            {
                mapID = 1454,
                x = 0.8380,
                y = 0.3160,
                label = "Drop under Orgrimmar",
                note = "Jump down past the gate area to get under Orgrimmar. The video notes there is mostly empty space underneath; hearth to leave.",
            },
        },
    },
    {
        id = "winterspring-hyjal-darkwhisper-video-guide",
        name = "Winterspring to Mount Hyjal",
        category = "Hidden Areas",
        continent = "kalimdor",
        difficulty = "advanced",
        mapID = 1452,
        description = "Video-derived route into Mount Hyjal through Darkwhisper Gorge in southern Winterspring. Source: Cal, classic glitches video, https://www.youtube.com/watch?v=u6VmixOH6rg. Waypoints are approximate guide markers and should be refined with GPS captures.",
        waypoints = {
            {
                mapID = 1452,
                x = 0.5940,
                y = 0.8420,
                label = "Darkwhisper Gorge",
                note = "Enter southern Winterspring at Darkwhisper Gorge. Expect level 59 elite mobs through the tunnel network.",
            },
            {
                mapID = 1452,
                x = 0.6000,
                y = 0.8710,
                label = "Find the pillar",
                note = "Work through the gorge until you find the pillar used for the wall jump. This is approximate and needs GPS refinement.",
            },
            {
                mapID = 1452,
                x = 0.6070,
                y = 0.8900,
                label = "Wall jump the pillar",
                note = "Wall jump up the pillar. The video shows this taking a while, so expect repeated jump attempts.",
            },
            {
                mapID = 1452,
                x = 0.6130,
                y = 0.9020,
                label = "Recover above gorge",
                note = "Once you make it up, stabilize your position before continuing. Falling here means repeating the pillar climb.",
            },
            {
                mapID = 1452,
                x = 0.6240,
                y = 0.9150,
                label = "Trees and hills",
                note = "Continue with more jumps around trees and hills, similar to mountain climbing routes like Ironforge Airstrip.",
            },
            {
                mapID = 1452,
                x = 0.6350,
                y = 0.9270,
                label = "Hyjal overlook",
                note = "You should eventually overlook Hyjal. Do not jump down immediately; the video warns this can put you behind an invisible wall.",
            },
            {
                mapID = 1452,
                x = 0.6530,
                y = 0.9350,
                label = "Traverse farther",
                note = "Traverse the mountains farther before dropping into Hyjal.",
            },
            {
                mapID = 1452,
                x = 0.6710,
                y = 0.9420,
                label = "Jump into Hyjal",
                note = "Jump down here after bypassing the invisible wall area. You should be able to explore toward the Hyjal Summit portal and Nordrassil.",
            },
        },
    },
    {
        id = "ironforge-old-ironforge-video-guide",
        name = "Old Ironforge",
        category = "Hidden Areas",
        continent = "eastern-kingdoms",
        difficulty = "advanced",
        mapID = 1455,
        description = "Video-derived mage Blink route into Old Ironforge. Source: Cal, classic glitches video, https://www.youtube.com/watch?v=u6VmixOH6rg. Waypoints are approximate guide markers and should be refined with GPS captures.",
        waypoints = {
            {
                mapID = 1455,
                x = 0.4040,
                y = 0.4950,
                label = "Old Ironforge door",
                note = "Start near the closed Old Ironforge door in the Great Forge. This route requires a mage with Blink.",
            },
            {
                mapID = 1455,
                x = 0.3950,
                y = 0.5050,
                label = "Wall jump edge",
                note = "Walk out from the door and wall jump up the edge. Keep jumping until you reach the height shown in the video.",
            },
            {
                mapID = 1455,
                x = 0.3880,
                y = 0.5140,
                label = "Blink height",
                note = "At about this height, Blink. You should end up on the other side of the wall above the door.",
            },
            {
                mapID = 1455,
                x = 0.3980,
                y = 0.5280,
                label = "Drop behind door",
                note = "Drop down behind the Old Ironforge door.",
            },
            {
                mapID = 1455,
                x = 0.4120,
                y = 0.5480,
                label = "Down the ramp",
                note = "Go down the ramp into Old Ironforge. The video notes the only practical way out is to hearth.",
            },
        },
    },
}
