local addonName, TEJ = ...

TEJ.Routes = {
    {
        id = "loch-modan-ironforge-airport-farms",
        name = "Loch Modan to Ironforge Airport / Farms",
        category = "Hidden Areas",
        continent = "eastern-kingdoms",
        difficulty = "easy",
        mapID = 1432,
        description = "A cross-zone mountain route from Loch Modan into Dun Morogh toward the Ironforge Airport and farms.",
        waypoints = {
            {
                mapID = 1432,
                x = 0.1957,
                y = 0.1521,
                label = "Starting mountain latch",
                note = "Continue jumping at the mountain until you latch on, and are able to jump once more up the mountain. This step can be tricky and take awhile.",
            },
            {
                mapID = 1432,
                x = 0.1904,
                y = 0.1420,
                label = "Hug left up the mountain",
                note = "Be sure to continue up the mountain, hugging left.",
            },
            {
                mapID = 1432,
                x = 0.1833,
                y = 0.1456,
                label = "Past the first tree",
                note = "Go past the tree and its textures, until you reach the next tree.",
            },
            {
                mapID = 1432,
                x = 0.1744,
                y = 0.1441,
                label = "Past the next trees",
                note = "Continue up the mountain, going past the next two trees.",
            },
            {
                mapID = 1432,
                x = 0.1646,
                y = 0.1275,
                label = "Left past blocking tree",
                note = "After passing the second tree, hang a left and jump past the tree that is in the way of the path.",
            },
            {
                mapID = 1432,
                x = 0.1514,
                y = 0.1367,
                label = "Keep left and climb",
                note = "Once past the tree, continue to hang a left and go up the mountain.",
            },
            {
                mapID = 1432,
                x = 0.1444,
                y = 0.1547,
                label = "Right up steep hill",
                note = "Be sure to hang a right here, going up the steep hill. You should be able to run directly up the hill.",
            },
            {
                mapID = 1432,
                x = 0.1268,
                y = 0.1514,
                label = "Right and climb again",
                note = "Once down the hill, be sure to go right and up the hill again. You should be able to run up the hill.",
            },
            {
                mapID = 1432,
                x = 0.1257,
                y = 0.1067,
                label = "Left side descent",
                note = "Once at the top of the hill, go back down the hill staying on the left hand side of the mountain.",
            },
            {
                mapID = 1426,
                x = 0.8526,
                y = 0.2179,
                label = "Dun Morogh snow line",
                note = "Once down the hill, keep walking forward and take a right. When you reach this waypoint you should be in Dun Morogh now. Keep following the snow to the next waypoint.",
            },
            {
                mapID = 1426,
                x = 0.7958,
                y = 0.2107,
                label = "Slight right to snowy hill",
                note = "At this waypoint, be sure to take a slight right toward the fully snowy looking hill.",
            },
            {
                mapID = 1426,
                x = 0.7691,
                y = 0.1766,
                label = "Dead tree ahead",
                note = "Now at the top of the snowy hill, head toward the dead tree right in front of you.",
            },
            {
                mapID = 1426,
                x = 0.7507,
                y = 0.1501,
                label = "Sharp left at dead tree",
                note = "Once at the dead tree, take a sharp left. Continue forward to the next waypoint.",
            },
            {
                mapID = 1426,
                x = 0.7225,
                y = 0.1570,
                label = "Sharp left again",
                note = "At this waypoint, take a sharp left once more.",
            },
            {
                mapID = 1426,
                x = 0.7215,
                y = 0.1789,
                label = "Ironforge Airport / Farms",
                note = "Congratulations! You should now see buildings and are free to explore the airport as you please!",
            },
        },
    },
    {
        id = "tanaris-caverns-of-time-video-guide",
        name = "Tanaris to Caverns of Time",
        category = "Hidden Areas",
        continent = "kalimdor",
        difficulty = "advanced",
        mapID = 1446,
        description = "Video-derived route for entering the closed Caverns of Time area in Classic. Source: SweetJohnnyCage, Caverns of Time Access Guide + Exploration, https://www.youtube.com/watch?v=V5xR9SCoP-0. Only the start coordinate is exact from the video transcript; later waypoints are approximate guide markers for refinement with GPS waypoints.",
        waypoints = {
            {
                mapID = 1446,
                x = 0.6756,
                y = 0.5600,
                label = "Start at Caverns ridge",
                note = "Go to Tanaris 67,56 on the southern side of the Caverns of Time mountain range. This is the exact coordinate called out in the video.",
            },
            {
                mapID = 1446,
                x = 0.6768,
                y = 0.5538,
                label = "Climb toward the ruins",
                note = "Run up the hill toward the ruin-looking structure. Expect a small amount of wall walking before the ruin approach.",
            },
            {
                mapID = 1446,
                x = 0.6810,
                y = 0.5500,
                label = "Visible edge attempt",
                note = "Try to catch on the visible edge of the ruin and walk up. The video notes this may not work reliably in Classic.",
            },
            {
                mapID = 1446,
                x = 0.6832,
                y = 0.5480,
                label = "Fear boost position",
                note = "If the wall-walk is too steep, duel a helper with Fear or similar loss-of-control ability, such as priest, warlock, or warrior. Have them fear you here to push you up onto the higher area.",
            },
            {
                mapID = 1446,
                x = 0.6860,
                y = 0.5440,
                label = "Follow the mountain",
                note = "Once above the ruin, follow the mountain route upward toward the ridge.",
            },
            {
                mapID = 1446,
                x = 0.6895,
                y = 0.5390,
                label = "Walk the ledge",
                note = "Walk along the ledge. If it feels risky, toggle walk with numpad slash and edge around carefully.",
            },
            {
                mapID = 1446,
                x = 0.6950,
                y = 0.5350,
                label = "Tower overlook",
                note = "Move toward the tower overlook that is visible from the Caverns of Time area in Tanaris.",
            },
            {
                mapID = 1446,
                x = 0.7000,
                y = 0.5310,
                label = "Black box jump",
                note = "Jump off near the black box/object shown in the video and aim to land on the brown mountain surface below.",
            },
            {
                mapID = 1446,
                x = 0.7035,
                y = 0.5275,
                label = "Heal before next jump",
                note = "Heal to full before continuing. Eat, bandage, or use healing spells because the next drop is large.",
            },
            {
                mapID = 1446,
                x = 0.7070,
                y = 0.5225,
                label = "Purple window jump",
                note = "Head toward the purple window. Run into it and jump so you glide down toward the right-hand ledge.",
            },
            {
                mapID = 1446,
                x = 0.7115,
                y = 0.5180,
                label = "Behind the door",
                note = "After landing on the ledge, jump down behind the door to enter the Caverns of Time area.",
            },
            {
                mapID = 1446,
                x = 0.7140,
                y = 0.5140,
                label = "Caverns of Time",
                note = "You should be inside the closed Caverns of Time area. The video notes the portals do not function; hearth out or die to leave.",
            },
        },
    },
    {
        id = "orgrimmar-under-city-video-guide",
        name = "Under Orgrimmar",
        category = "Hidden Areas",
        continent = "kalimdor",
        difficulty = "advanced",
        mapID = 1454,
        description = "Video-derived route for reaching the underside of Orgrimmar from the north side of Valley of Honor. Source: Cal, classic glitches video, https://www.youtube.com/watch?v=u6VmixOH6rg. Waypoints are approximate guide markers and should be refined with GPS captures.",
        waypoints = {
            {
                mapID = 1454,
                x = 0.7920,
                y = 0.3020,
                label = "North Valley of Honor",
                note = "Start at the north point of Orgrimmar in Valley of Honor. The video suggests a mount is likely required for the longer jumps.",
            },
            {
                mapID = 1454,
                x = 0.7980,
                y = 0.2860,
                label = "First rock climb",
                note = "Jump onto the rock section near the north wall. Keep adjusting until you can stand high enough to continue.",
            },
            {
                mapID = 1454,
                x = 0.8040,
                y = 0.2750,
                label = "Twig run-up",
                note = "Run up the twig or branch-like edge, then turn around and mount up for the longer jump.",
            },
            {
                mapID = 1454,
                x = 0.8120,
                y = 0.2820,
                label = "Mounted jump to rocks",
                note = "Use the mounted jump to reach the next rock section. Slow Fall was tried in the video but was not successful.",
            },
            {
                mapID = 1454,
                x = 0.8210,
                y = 0.2920,
                label = "Second stick jump",
                note = "Move around to the next stick-like edge. Mount again and line up the jump toward the building.",
            },
            {
                mapID = 1454,
                x = 0.8300,
                y = 0.3020,
                label = "Building landing",
                note = "Land on the building. From here you should be able to see areas beyond the gate that are not normally shown.",
            },
            {
                mapID = 1454,
                x = 0.8380,
                y = 0.3160,
                label = "Drop under Orgrimmar",
                note = "Jump down past the gate area to get under Orgrimmar. The video notes there is mostly empty space underneath; hearth to leave.",
            },
        },
    },
    {
        id = "winterspring-hyjal-darkwhisper-video-guide",
        name = "Winterspring to Mount Hyjal",
        category = "Hidden Areas",
        continent = "kalimdor",
        difficulty = "advanced",
        mapID = 1452,
        description = "Detailed route into Mount Hyjal through Darkwhisper Gorge in southern Winterspring. Primary sources: SoupaSoka, Vanilla WoW Secrets #11: Mount Hyjal, https://www.youtube.com/watch?v=5kuJowGULAk, and Tim's Variety Gaming, Wow Classic Exploration Part 9, https://www.youtube.com/watch?v=Vuf1apfBjtU. Start is anchored around Winterspring 53,83 from the source video; later ridge waypoints follow the described pillar, cliff, invisible-wall bypass, and final entry sequence.",
        waypoints = {
            {
                mapID = 1452,
                x = 0.5300,
                y = 0.8300,
                label = "Darkwhisper Gorge start",
                note = "Start in southern Winterspring around 53,83. Look for the Darkwhisper Gorge opening with two torches, a central pillar, and Hederine mobs nearby.",
            },
            {
                mapID = 1452,
                x = 0.5260,
                y = 0.8390,
                label = "Pillar base",
                note = "Walk up to the central stone pillar. Clear or avoid nearby elite mobs so you can focus on the jump.",
            },
            {
                mapID = 1452,
                x = 0.5230,
                y = 0.8460,
                label = "Catch pillar lip",
                note = "Make small jumps against the pillar until you land partway up on the lip. This can take repeated attempts.",
            },
            {
                mapID = 1452,
                x = 0.5210,
                y = 0.8530,
                label = "Walk around pillar",
                note = "Toggle walk and carefully move around the pillar lip to the far side. Falling means repeating the setup.",
            },
            {
                mapID = 1452,
                x = 0.5260,
                y = 0.8610,
                label = "Wedge and mount",
                note = "Mount up and wedge between the cliffside and pillar. Aim toward the cliffside gap between the two peaks near the tree.",
            },
            {
                mapID = 1452,
                x = 0.5360,
                y = 0.8670,
                label = "Mounted cliff jump",
                note = "Jump forward from the wedge and land on the cliffside. This mounted jump is the main gateway to the route.",
            },
            {
                mapID = 1452,
                x = 0.5480,
                y = 0.8730,
                label = "Left rocky outcroppings",
                note = "Go left across the rocky outcroppings above the blocked Hyjal portal cave. Stay high and do not drop into the invisible-wall area.",
            },
            {
                mapID = 1452,
                x = 0.5630,
                y = 0.8790,
                label = "Invisible wall bypass",
                note = "If you hit an invisible wall, move farther west. The Tim's Variety route notes this as the signal that you need to go around and over it.",
            },
            {
                mapID = 1452,
                x = 0.5790,
                y = 0.8870,
                label = "Track in cliffside",
                note = "Find the cliffside with the small track down the middle. Line up the final jump as close to the top of that path as possible.",
            },
            {
                mapID = 1452,
                x = 0.5920,
                y = 0.8980,
                label = "Final Hyjal jump",
                note = "Jump to the top of the little path. Once you land, you should be inside Mount Hyjal and able to begin exploring.",
            },
            {
                mapID = 1452,
                x = 0.6130,
                y = 0.9120,
                label = "Hyjal entry",
                note = "You are now in Hyjal. Watch for invisible walls around red portals, and bring a mount because the zone is very large.",
            },
            {
                mapID = 1452,
                x = 0.6420,
                y = 0.9300,
                label = "Dragon-mouth portal area",
                note = "Optional exploration: look for the dragon-mouth portal area similar to Onyxia's Lair. Tim's route notes it does not open.",
            },
            {
                mapID = 1452,
                x = 0.6680,
                y = 0.9500,
                label = "Explore deeper Hyjal",
                note = "Continue deeper into Hyjal toward the stone paths, ruins, crater, and Nordrassil area. Plan a hearth exit; dying here can cause a painful spirit resurrection.",
            },
        },
    },
    {
        id = "ironforge-old-ironforge-video-guide",
        name = "Old Ironforge",
        category = "Hidden Areas",
        continent = "eastern-kingdoms",
        difficulty = "advanced",
        mapID = 1455,
        description = "Video-derived mage Blink route into Old Ironforge. Source: Cal, classic glitches video, https://www.youtube.com/watch?v=u6VmixOH6rg. Waypoints are approximate guide markers and should be refined with GPS captures.",
        waypoints = {
            {
                mapID = 1455,
                x = 0.4040,
                y = 0.4950,
                label = "Old Ironforge door",
                note = "Start near the closed Old Ironforge door in the Great Forge. This route requires a mage with Blink.",
            },
            {
                mapID = 1455,
                x = 0.3950,
                y = 0.5050,
                label = "Wall jump edge",
                note = "Walk out from the door and wall jump up the edge. Keep jumping until you reach the height shown in the video.",
            },
            {
                mapID = 1455,
                x = 0.3880,
                y = 0.5140,
                label = "Blink height",
                note = "At about this height, Blink. You should end up on the other side of the wall above the door.",
            },
            {
                mapID = 1455,
                x = 0.3980,
                y = 0.5280,
                label = "Drop behind door",
                note = "Drop down behind the Old Ironforge door.",
            },
            {
                mapID = 1455,
                x = 0.4120,
                y = 0.5480,
                label = "Down the ramp",
                note = "Go down the ramp into Old Ironforge. The video notes the only practical way out is to hearth.",
            },
        },
    },
    {
        id = "stonetalon-peak-ridge-oob-video-guide",
        name = "Stonetalon Peak Ridge Out of Bounds",
        category = "Hidden Areas",
        continent = "kalimdor",
        difficulty = "advanced",
        mapID = 1442,
        description = "Video-derived route for climbing up and over the northern Stonetalon Peak ridge. Source: Not Miles Prower, Out of Bounds Discovery in Stonetalon Peak!, https://www.youtube.com/watch?v=h4JmYn9j7OE. The video has no captions and no exact coordinate overlay, so these are approximate guide markers intended for GPS refinement.",
        waypoints = {
            {
                mapID = 1442,
                x = 0.3650,
                y = 0.0720,
                label = "Stonetalon Peak",
                note = "Start at Stonetalon Peak near the den and flight point. This anchor is approximate, based on known Stonetalon Peak coordinates.",
            },
            {
                mapID = 1442,
                x = 0.3560,
                y = 0.0660,
                label = "Right side of the den",
                note = "Move to the right side of the den. Look for a slope or path that lets you begin climbing higher along the ridge.",
            },
            {
                mapID = 1442,
                x = 0.3480,
                y = 0.0590,
                label = "First ridge climb",
                note = "Start the first set of repeated jumps up the steep terrain. The video shows a natural-looking climb rather than a class ability requirement.",
            },
            {
                mapID = 1442,
                x = 0.3390,
                y = 0.0520,
                label = "Brown ridge shelf",
                note = "Reach the brown ridge shelf above the normal play area. Follow the ridge carefully and avoid sliding back down.",
            },
            {
                mapID = 1442,
                x = 0.3270,
                y = 0.0440,
                label = "Over the ridge",
                note = "Continue up and over the northern ridge. You should start seeing unfinished terrain and the outer edge of the playable map.",
            },
            {
                mapID = 1442,
                x = 0.3140,
                y = 0.0390,
                label = "Out-of-bounds run",
                note = "Run along the high out-of-bounds terrain. The video shows long stretches of bare mountain and steep drops.",
            },
            {
                mapID = 1442,
                x = 0.3010,
                y = 0.0480,
                label = "Drop toward green lowlands",
                note = "Find a safer descent toward the greener area below. Heal up first if you have taken fall damage.",
            },
            {
                mapID = 1442,
                x = 0.2890,
                y = 0.0610,
                label = "Hidden northern lowlands",
                note = "Explore the hidden northern Stonetalon terrain. The video shows water, grassy terrain, and distant edge-of-map scenery from here.",
            },
        },
    },
    {
        id = "mulgore-mountain-camp-video-guide",
        name = "Mulgore Mountain Camp / Cave",
        category = "Hidden Areas",
        continent = "kalimdor",
        difficulty = "advanced",
        mapID = 1412,
        description = "Video-derived route to an out-of-bounds mountain camp and cave in northern Mulgore, between the Crossroads and Thunder Bluff flight path. Source: Boosticuff, Mulgore Mountain Camp (Out of Bounds), https://www.youtube.com/watch?v=wviIBpRFy5I. The starting map frame shows the player near Mulgore 65.1, 10.8; later waypoints are approximate guide markers intended for GPS refinement.",
        waypoints = {
            {
                mapID = 1412,
                x = 0.6510,
                y = 0.1080,
                label = "Starting mountain wall",
                note = "Start in northern Mulgore around 65.1, 10.8, near the eastern mountain wall. This is the approximate player coordinate visible in the video map frame.",
            },
            {
                mapID = 1412,
                x = 0.6440,
                y = 0.0990,
                label = "Begin the climb",
                note = "Face the mountain and begin jumping up the sloped wall. Look for small ledges where your character can catch and stand.",
            },
            {
                mapID = 1412,
                x = 0.6350,
                y = 0.0900,
                label = "Work left along the face",
                note = "Continue climbing while edging left along the mountain face. The video shows repeated short jumps rather than a class-specific trick.",
            },
            {
                mapID = 1412,
                x = 0.6250,
                y = 0.0800,
                label = "High orange shelf",
                note = "Reach the higher orange-brown shelf. From here, keep following the ridge upward toward the hidden camp.",
            },
            {
                mapID = 1412,
                x = 0.6120,
                y = 0.0700,
                label = "Mountain top",
                note = "Arrive on top of the mountain. You should be above the normal Mulgore terrain and able to look down toward the valley.",
            },
            {
                mapID = 1412,
                x = 0.5980,
                y = 0.0610,
                label = "Hidden camp",
                note = "Explore the small hidden camp area. The video shows scenic flight-path decoration rather than a normal quest hub.",
            },
            {
                mapID = 1412,
                x = 0.5860,
                y = 0.0550,
                label = "Painted rocks",
                note = "Look for animal paintings on the rocks. The video notes these markings seem unique to this hidden area.",
            },
            {
                mapID = 1412,
                x = 0.5750,
                y = 0.0500,
                label = "Cave mouth",
                note = "Move toward the cave entrance near the camp. There are no NPCs shown in the video.",
            },
            {
                mapID = 1412,
                x = 0.5680,
                y = 0.0460,
                label = "Inside the cave",
                note = "Enter and explore the cave interior. This appears to be a scenic out-of-bounds cave used for flight path ambience.",
            },
        },
    },
    {
        id = "shatterspear-village-winterspring-route",
        name = "Winterspring to Shatterspear Village",
        category = "Hidden Areas",
        continent = "kalimdor",
        difficulty = "advanced",
        mapID = 1452,
        description = "Detailed video-derived route to Shatterspear Village / Dancing Troll Village. Primary source: SoupaSoka, Vanilla WoW Secrets #1: Shatterspear Village, https://www.youtube.com/watch?v=1eARibEKumU. Supporting source: Tim's Variety Gaming, Wow Classic Exploration Part 16, https://www.youtube.com/watch?v=JAzze2ND2SE, plus Wowhead Classic Shatterspear Troll route notes. Requires a mount and a fall-damage solution such as Slow Fall, Noggenfogger slow fall, paladin bubble, reincarnation, or strong Safe Fall.",
        waypoints = {
            {
                mapID = 1452,
                x = 0.2780,
                y = 0.3460,
                label = "Outside Timbermaw Hold",
                note = "Start in western Winterspring, outside Timbermaw Hold. The video starts in the top-left corner of Winterspring with Timbermaw Hold visible nearby. Mount speed is strongly recommended.",
            },
            {
                mapID = 1452,
                x = 0.2690,
                y = 0.3370,
                label = "Right-side cliff start",
                note = "Run along the right side of the cliff above the Timbermaw approach. Begin climbing toward the trees on the ridge.",
            },
            {
                mapID = 1452,
                x = 0.2600,
                y = 0.3270,
                label = "Two-tree path",
                note = "Pass the two trees, take the path to the right around the small tree, then curve left.",
            },
            {
                mapID = 1452,
                x = 0.2520,
                y = 0.3150,
                label = "Big tree squeeze",
                note = "Move around the big tree to the right. Spam jump if you catch on the edge until you can sneak behind it.",
            },
            {
                mapID = 1452,
                x = 0.2440,
                y = 0.3020,
                label = "Crest above the tree",
                note = "Once above the big tree, look for a small pine tree to the left, then run up the steep-looking hill toward Felwood.",
            },
            {
                mapID = 1448,
                x = 0.6510,
                y = 0.0710,
                label = "Felwood border ridge",
                note = "You should cross into Felwood near the north-northeast corner by the Timbermaw entrance. Keep running uphill and slightly right.",
            },
            {
                mapID = 1448,
                x = 0.6350,
                y = 0.0580,
                label = "Straight through the trees",
                note = "Continue straight through the trees. The snow should start giving way to darker Felwood terrain in the distance.",
            },
            {
                mapID = 1448,
                x = 0.6120,
                y = 0.0490,
                label = "Left ridge transfer",
                note = "Follow the ridge line, then move over to the hill on the left. The next section has a series of gap jumps.",
            },
            {
                mapID = 1448,
                x = 0.5890,
                y = 0.0430,
                label = "First long gap",
                note = "Make a mounted full-speed jump toward the small bump across the gap. Missing this is recoverable but awkward.",
            },
            {
                mapID = 1448,
                x = 0.5680,
                y = 0.0410,
                label = "Second gap jump",
                note = "Jump straight across the next small gap without clipping the mountain side. If you fall into the little rock pocket, fight your way back up.",
            },
            {
                mapID = 1448,
                x = 0.5460,
                y = 0.0450,
                label = "Crevice long jump",
                note = "Drop into the narrow crack, then angle slightly left and make the long jump to the safe spot on the left side.",
            },
            {
                mapID = 1448,
                x = 0.5200,
                y = 0.0540,
                label = "Over the hill",
                note = "Dismount if needed, cross over the hill, then drop left and continue upward until the terrain opens toward Moonglade/Darkshore.",
            },
            {
                mapID = 1450,
                x = 0.3150,
                y = 0.9250,
                label = "Southwest Moonglade high point",
                note = "You should now be on the southwest edge of Moonglade, physically above the Darkshore side. Heal to full and prepare a fall-damage solution.",
            },
            {
                mapID = 1450,
                x = 0.2960,
                y = 0.9360,
                label = "Walk down the ledge",
                note = "Toggle walk and step down slowly. This descent can kill most classes without Slow Fall, Noggenfogger, bubble, reincarnation, or Safe Fall.",
            },
            {
                mapID = 1450,
                x = 0.2760,
                y = 0.9490,
                label = "Tree slide descent",
                note = "Slide down by the tree, then heal again. The video shows another large fall before reaching the final approach.",
            },
            {
                mapID = 1439,
                x = 0.7430,
                y = 0.1450,
                label = "Darkshore lake view",
                note = "You should cross into Darkshore and begin seeing the hidden lake and bridge below. Stay cautious; the village is close but the falls remain dangerous.",
            },
            {
                mapID = 1439,
                x = 0.7570,
                y = 0.1330,
                label = "Final safe drop",
                note = "Slow-walk or Slow Fall down the final ledges toward the bridge. Jump only when you are sure the next landing is survivable.",
            },
            {
                mapID = 1439,
                x = 0.7710,
                y = 0.1210,
                label = "Shatterspear bridge",
                note = "Land near the bridge into Shatterspear Village. This village is east of the Ruins of Mathystra on the hidden far-eastern mountain side.",
            },
            {
                mapID = 1439,
                x = 0.7850,
                y = 0.1160,
                label = "Shatterspear Village",
                note = "Explore the dancing trolls, huts, bridge, lake, cave, and named NPCs. The video notes there is no easy normal exit, so plan to hearth or die.",
            },
        },
    },
    {
        id = "wetlands-to-newmans-landing",
        name = "Wetlands to Newman's Landing",
        category = "Hidden Areas",
        continent = "eastern-kingdoms",
        difficulty = "easy",
        mapID = 1437,
        description = "Coastal swim route to Newman's Landing, a tiny hidden camp on the far western Dun Morogh coast. Sources: Warcraft Wiki / Wowpedia Newman's Landing notes and classic community route notes describe the location around Dun Morogh 11,76 and suggest reaching it by swimming along the western coastline. This path starts from Menethil Harbor and hugs the shore to reduce fatigue risk.",
        waypoints = {
            {
                mapID = 1437,
                x = 0.0990,
                y = 0.5950,
                label = "Menethil Harbor",
                note = "Start at Menethil Harbor in Wetlands. Get into the water on the west side of the harbor and prepare for a long coastal swim.",
            },
            {
                mapID = 1437,
                x = 0.0860,
                y = 0.6620,
                label = "Leave the harbor coast",
                note = "Swim south along the western coastline. Stay close enough to shore that the fatigue bar does not become dangerous.",
            },
            {
                mapID = 1437,
                x = 0.0730,
                y = 0.7420,
                label = "Western Wetlands coast",
                note = "Continue following the coast south. If fatigue appears, angle closer to land before continuing.",
            },
            {
                mapID = 1437,
                x = 0.0600,
                y = 0.8380,
                label = "Southwest Wetlands bend",
                note = "Keep rounding the southwestern edge of Wetlands. Do not cut too far into the open water.",
            },
            {
                mapID = 1437,
                x = 0.0520,
                y = 0.9120,
                label = "Zone border swim",
                note = "Follow the coastline into the Dun Morogh map area. The overlay will continue on the Dun Morogh zone map.",
            },
            {
                mapID = 1426,
                x = 0.0540,
                y = 0.2120,
                label = "Dun Morogh north coast",
                note = "You should now be on the far northwest coast of Dun Morogh. Keep swimming south with the coastline on your left.",
            },
            {
                mapID = 1426,
                x = 0.0620,
                y = 0.3660,
                label = "Long western coastline",
                note = "Continue south. This route is simple but slow; the main danger is drifting too far west into fatigue water.",
            },
            {
                mapID = 1426,
                x = 0.0740,
                y = 0.5240,
                label = "Keep hugging shore",
                note = "Stay near the shore and keep following the west coast down toward the hidden camp.",
            },
            {
                mapID = 1426,
                x = 0.0910,
                y = 0.6760,
                label = "Approach the landing",
                note = "Begin watching for a tiny camp on the coastline. The destination is close.",
            },
            {
                mapID = 1426,
                x = 0.1100,
                y = 0.7600,
                label = "Newman's Landing",
                note = "Arrive at Newman's Landing, the hidden coastal camp around Dun Morogh 11,76. Explore the small dock/camp area, then hearth or swim back out.",
            },
        },
    },
    {
        id = "zulmashar-to-epl-backside",
        name = "Zul'Mashar to EPL Backside / Quel'Thalas Edge",
        category = "Hidden Areas",
        continent = "eastern-kingdoms",
        difficulty = "advanced",
        mapID = 1423,
        description = "Mountain-jump route from Zul'Mashar into the unfinished terrain north of Eastern Plaguelands, with views of the Stratholme backside and the Quel'Thalas edge. Primary source: Concerned Mom, Classic WoW exploration above Eastern Plaguelands, https://www.youtube.com/watch?v=rkEoS8bj5H0. Supporting source: SoupaSoka, Eastern Plaguelands Tower / Quel'thalas swim route, https://www.youtube.com/watch?v=OrPnFV5MXRE. Start is anchored at the known Zul'Mashar area; ridge waypoints are approximate and should be GPS-refined.",
        waypoints = {
            {
                mapID = 1423,
                x = 0.6600,
                y = 0.1050,
                label = "Zul'Mashar altar",
                note = "Start at Zul'Mashar in northern Eastern Plaguelands, at the troll altar area. Avoid aggroing shadow hunters if possible because you will need to mount soon.",
            },
            {
                mapID = 1423,
                x = 0.6660,
                y = 0.0980,
                label = "Back corner drop",
                note = "Move to the back of the altar and drop to the small corner ledge. Face the flat rock surface across the gap.",
            },
            {
                mapID = 1423,
                x = 0.6730,
                y = 0.0920,
                label = "Flat rock jump",
                note = "Jump across to the flat rock. The video notes this first jump is makeable without a mount; if missed, climb back around and try again.",
            },
            {
                mapID = 1423,
                x = 0.6790,
                y = 0.0860,
                label = "Climb right",
                note = "Edge slightly up and to the right, then jump up onto the top of the rock. Mount up once you are stable.",
            },
            {
                mapID = 1423,
                x = 0.6880,
                y = 0.0800,
                label = "Mounted crevice jump",
                note = "Line up the mounted jump into the small crevice ahead. This is the key jump that opens the path into the unfinished ridge.",
            },
            {
                mapID = 1423,
                x = 0.7000,
                y = 0.0730,
                label = "Untextured ridge",
                note = "Walk into the zone above Eastern Plaguelands. Watch for untextured ground and sudden cliff edges.",
            },
            {
                mapID = 1423,
                x = 0.7140,
                y = 0.0670,
                label = "First cliff wall",
                note = "Do not run straight off the sheer cliff. If you have Slow Fall or Levitate, you can drop later; otherwise use the safer ramp on the right side.",
            },
            {
                mapID = 1423,
                x = 0.6970,
                y = 0.0550,
                label = "Left upper ridge",
                note = "Follow the left side of the upper ridge first. This gives a look at the unfinished mountains and the terrain behind the blood elf ambassador barrier.",
            },
            {
                mapID = 1423,
                x = 0.6760,
                y = 0.0470,
                label = "Texture split",
                note = "Continue along the split between textured and untextured terrain. Stay on the upper shelf and avoid dropping into pockets you cannot climb out of.",
            },
            {
                mapID = 1423,
                x = 0.6540,
                y = 0.0420,
                label = "Upper shelf end",
                note = "The upper shelf eventually breaks down to a lower plateau. Do not step off the final sheer edge unless you have a fall-damage solution.",
            },
            {
                mapID = 1423,
                x = 0.7200,
                y = 0.0550,
                label = "Safe ramp side",
                note = "If you do not have Slow Fall or Levitate, circle back toward the right-side ramp to descend safely to the lower plateau.",
            },
            {
                mapID = 1423,
                x = 0.7040,
                y = 0.0750,
                label = "Lower plateau",
                note = "Reach the lower plateau north of Eastern Plaguelands. From here you can explore safely as long as you do not drop off the next cliff edge.",
            },
            {
                mapID = 1423,
                x = 0.6850,
                y = 0.0960,
                label = "Stratholme backside view",
                note = "Move toward the back of Stratholme. The video shows views of the instance portal backsides and unfinished city terrain from this plateau.",
            },
            {
                mapID = 1423,
                x = 0.6680,
                y = 0.1160,
                label = "Portal overlook",
                note = "This is a good overlook for the Stratholme portals from behind. Use caution around drops; dying here can mean an awkward corpse run or spirit resurrection.",
            },
            {
                mapID = 1423,
                x = 0.6500,
                y = 0.1350,
                label = "Continue exploring",
                note = "Continue along the northern unfinished terrain as desired. Plan your exit before going too far; hearthstone is the safest way out.",
            },
        },
    },
    {
        id = "tirisfal-coast-to-quelthalas-tower",
        name = "Tirisfal Coast to Quel'Thalas Tower",
        category = "Hidden Areas",
        continent = "eastern-kingdoms",
        difficulty = "intermediate",
        mapID = 1420,
        description = "Coastal swim route from the northern Tirisfal Glades coast to the Quel'Thalas tower remnant north of Eastern Plaguelands. Primary source: SoupaSoka, Vanilla WoW Secrets #3: Eastern Plaguelands Tower / Quel'thalas, https://www.youtube.com/watch?v=OrPnFV5MXRE. Supporting references: Warcraft Wiki / Wowpedia notes describe the tower remnant as reachable by swimming from northern Tirisfal while staying close to shore to avoid fatigue.",
        waypoints = {
            {
                mapID = 1420,
                x = 0.7770,
                y = 0.1180,
                label = "Northern Tirisfal beach",
                note = "Start from the northern Tirisfal Glades coast. The source route begins on the beach and heads east along the northern edge of the zone.",
            },
            {
                mapID = 1420,
                x = 0.8120,
                y = 0.0960,
                label = "Northeast coast",
                note = "Follow the beach toward the northeast corner of Tirisfal. Swim-speed gear, Aquatic Form, or Water Walking makes the route faster and safer.",
            },
            {
                mapID = 1420,
                x = 0.8520,
                y = 0.0740,
                label = "Enter the water",
                note = "Enter the water at the far northeast coast and begin swimming around the otherwise unreachable mountain wall.",
            },
            {
                mapID = 1420,
                x = 0.8920,
                y = 0.0520,
                label = "Hug the cliff",
                note = "Stay very close to the cliff-water edge. The video warns that drifting outward triggers fatigue, and the fatigue bar can kill you.",
            },
            {
                mapID = 1420,
                x = 0.9320,
                y = 0.0410,
                label = "Fatigue edge",
                note = "Keep swimming east along the cliff. If fatigue appears, angle back toward the rock wall before continuing.",
            },
            {
                mapID = 1420,
                x = 0.9720,
                y = 0.0460,
                label = "Round the headland",
                note = "Round the headland carefully. The source video shows several flat shoreline shelves, but they do not contain much of interest.",
            },
            {
                mapID = 1423,
                x = 0.5750,
                y = 0.0080,
                label = "Northern EPL waters",
                note = "The route now approaches the northern side of Eastern Plaguelands / Quel'Thalas edge terrain. Continue hugging the coast.",
            },
            {
                mapID = 1423,
                x = 0.6120,
                y = 0.0060,
                label = "Tower in sight",
                note = "Watch for a white tower and ruins in the distance. This is the destination shown in the source video.",
            },
            {
                mapID = 1423,
                x = 0.6460,
                y = 0.0080,
                label = "Dock approach",
                note = "Swim toward the shoreline with the dock, rubble, and elven-looking tower. Approach from the water side.",
            },
            {
                mapID = 1423,
                x = 0.6650,
                y = 0.0110,
                label = "Quel'Thalas tower",
                note = "Land at the Quel'Thalas tower remnant north of Eastern Plaguelands. Explore the tower, dock, rubble, and shoreline; hearthstone is the simplest exit.",
            },
        },
    },
    {
        id = "arathi-hidden-dwarven-farm",
        name = "Arathi Hidden Dwarven Farm",
        category = "Hidden Areas",
        continent = "eastern-kingdoms",
        difficulty = "easy",
        mapID = 1417,
        description = "Long shoreline swim from the southern Arathi Highlands coast to the hidden dwarven farm on the far eastern coast. Primary video source: WoWHiddenPlaces, WoW Hidden Places: The Hidden Arathi Farm, https://www.youtube.com/watch?v=X-PcnFvnH-o. Supporting references: Warcraft Wiki / WoWWiki Hidden Dwarf Farm notes place the farm near Arathi Highlands 92,70 and describe swimming from the bottom of Arathi or from the Thandol Span / Wetlands side.",
        waypoints = {
            {
                mapID = 1417,
                x = 0.4550,
                y = 0.8870,
                label = "Bottom of Arathi",
                note = "Start on the southern Arathi Highlands coast, near the Thandol Span side. This follows the video approach of swimming from the bottom of Arathi.",
            },
            {
                mapID = 1417,
                x = 0.5350,
                y = 0.9020,
                label = "Southern coast swim",
                note = "Enter the water and swim east along the southern shoreline. Stay close enough to the land that you can correct course if fatigue appears.",
            },
            {
                mapID = 1417,
                x = 0.6200,
                y = 0.8940,
                label = "Pass the low coast",
                note = "Continue east past the low southern coastline. The route is a long swim, so swim-speed potions, Aquatic Form, or Water Walking can help, but are not required.",
            },
            {
                mapID = 1417,
                x = 0.7050,
                y = 0.8640,
                label = "Southeast bend",
                note = "Begin curving northeast around the southeastern edge of Arathi. Keep the coastline on your left and avoid swimming too far into open water.",
            },
            {
                mapID = 1417,
                x = 0.7850,
                y = 0.8150,
                label = "Eastern shelf",
                note = "Follow the eastern shelf northward. The hidden farm is still ahead; do not turn inland until the coastline flattens out near the far eastern side.",
            },
            {
                mapID = 1417,
                x = 0.8500,
                y = 0.7550,
                label = "Farm hills ahead",
                note = "Watch the shoreline for grassy hills and dwarven buildings. Angle toward land once the terrain opens up instead of continuing along the cliff edge.",
            },
            {
                mapID = 1417,
                x = 0.8970,
                y = 0.7180,
                label = "Shore approach",
                note = "Swim directly toward the farm shoreline. This is the final approach shown by the video and matches the known hidden farm location on the far eastern coast.",
            },
            {
                mapID = 1417,
                x = 0.9200,
                y = 0.7000,
                label = "Hidden Dwarven Farm",
                note = "Land at the hidden dwarven farm near Arathi Highlands 92,70. Explore the farm buildings and shoreline; hearthstone is the simplest exit when finished.",
            },
        },
    },
    {
        id = "deadwind-karazhan-crypts-ghost-gate",
        name = "Deadwind Pass to Karazhan Crypts",
        category = "Hidden Areas",
        continent = "eastern-kingdoms",
        difficulty = "advanced",
        mapID = 1430,
        description = "Route to Morgan's Plot and the Karazhan Crypts gate beneath Karazhan. Sources: Warcraft Wiki / Wowpedia Karazhan Crypts and Morgan's Plot notes describe the crypt entrance at Morgan's Plot in southern Deadwind Pass, and older exploration guides describe the ghost-gate method used to resurrect past the barred entrance. This can depend on the current Classic Era client behavior, so treat the final ghost step as the part to verify live.",
        waypoints = {
            {
                mapID = 1430,
                x = 0.0750,
                y = 0.4510,
                label = "Duskwood road entry",
                note = "Enter Deadwind Pass from the Duskwood road. Follow the main road east into the zone and stay mounted if possible.",
            },
            {
                mapID = 1430,
                x = 0.1900,
                y = 0.4950,
                label = "Main road bend",
                note = "Continue along the main road. Avoid pulling extra mobs if you are low level, since the final trick requires a controlled death near Karazhan.",
            },
            {
                mapID = 1430,
                x = 0.3200,
                y = 0.5450,
                label = "Turn south",
                note = "At the road split, turn south toward Karazhan instead of continuing deeper into the pass.",
            },
            {
                mapID = 1430,
                x = 0.4050,
                y = 0.6530,
                label = "Karazhan approach",
                note = "Follow the road up toward Karazhan. Keep moving past the tower approach and look for the graveyard / crypt grounds below the tower.",
            },
            {
                mapID = 1430,
                x = 0.4700,
                y = 0.7410,
                label = "Tower road",
                note = "Pass the main Karazhan tower approach. The crypt entrance is not the raid entrance; it is down at Morgan's Plot, south and slightly west of the tower.",
            },
            {
                mapID = 1430,
                x = 0.4300,
                y = 0.7720,
                label = "Drop to Morgan's Plot",
                note = "Move down toward Morgan's Plot. You are looking for the barred crypt gate set into the hillside below Karazhan.",
            },
            {
                mapID = 1430,
                x = 0.3900,
                y = 0.7400,
                label = "Crypt gate",
                note = "Stand directly at the barred Karazhan Crypts gate. Older guides use a controlled death here, then run the ghost through the gate before resurrecting.",
            },
            {
                mapID = 1430,
                x = 0.3870,
                y = 0.7420,
                label = "Die at the bars",
                note = "Die with your body pressed close to the bars. The goal is to leave your corpse near enough that the resurrection prompt can appear from the other side.",
            },
            {
                mapID = 1430,
                x = 0.3920,
                y = 0.7460,
                label = "Ghost through",
                note = "As a ghost, move through the gate and stand just inside the crypt. Adjust your position until the resurrect prompt appears.",
            },
            {
                mapID = 1430,
                x = 0.3970,
                y = 0.7510,
                label = "Resurrect inside",
                note = "Accept resurrection from inside the gate. If the prompt will not appear, move slightly back toward the bars and try again; hearthstone is the clean exit after exploring.",
            },
        },
    },
    {
        id = "ironforge-airfield-to-wetlands-farm",
        name = "Ironforge Airfield to Wetlands Farm",
        category = "Hidden Areas",
        continent = "eastern-kingdoms",
        difficulty = "easy",
        mapID = 1426,
        description = "Route from the Ironforge Airfield down to the isolated Wetlands Farm behind Ironforge. Primary video source: Hacco, How to reach the Wetlands Farm from the Ironforge Airfield in Classic WoW, https://www.youtube.com/watch?v=F4_YURx8VLs. Supporting source: Tim's Variety Gaming, WoW Classic Exploration Part 2 - Farms & Tunnel To Nothing, https://www.youtube.com/watch?v=IXqJROoBm1I. Location anchors: Ironforge Airfield is around Dun Morogh 77.9,22.5, and the Wetlands Farm is commonly referenced around Wetlands 24,68.",
        waypoints = {
            {
                mapID = 1426,
                x = 0.7790,
                y = 0.2250,
                label = "Ironforge Airfield",
                note = "Start at the Ironforge Airfield. This route assumes you have already reached the airfield by the Loch Modan / airport route or another method.",
            },
            {
                mapID = 1426,
                x = 0.8100,
                y = 0.2050,
                label = "East along mountains",
                note = "Head east along the northern mountainside, as shown in the Hacco route. Stay high on the snowy edge and keep the cliff to your left.",
            },
            {
                mapID = 1426,
                x = 0.8350,
                y = 0.1820,
                label = "Northern ridge",
                note = "Continue along the ridge toward the greener Wetlands side. Slow Fall, Safe Fall, Levitate, or similar tools make the descent safer but are not required by the source route.",
            },
            {
                mapID = 1437,
                x = 0.2050,
                y = 0.7250,
                label = "Follow slope down",
                note = "Cross into the Wetlands-side mountain terrain and follow the slope down carefully. Do not jump straight off the cliff unless you are using a fall-safety method.",
            },
            {
                mapID = 1437,
                x = 0.2140,
                y = 0.7040,
                label = "Careful descent",
                note = "Carefully make your way down the hillside. Use small ledges and angled terrain to bleed off height before the final drop.",
            },
            {
                mapID = 1437,
                x = 0.2240,
                y = 0.6880,
                label = "North side drop",
                note = "Fall down the northern side of this hill, matching the video route. Aim for the sloped ground, not the steep pits or dark gaps nearby.",
            },
            {
                mapID = 1437,
                x = 0.2380,
                y = 0.6760,
                label = "Go west safely",
                note = "Once on the lower terrain, go west toward the farm area. The video warns not to fall into the large pits along this stretch.",
            },
            {
                mapID = 1437,
                x = 0.2480,
                y = 0.6810,
                label = "Wetlands Farm",
                note = "Arrive at the isolated Wetlands Farm behind Ironforge. This is a good place to explore, fish, or meet up before continuing toward the tunnel.",
            },
            {
                mapID = 1437,
                x = 0.2680,
                y = 0.6740,
                label = "Past the farm",
                note = "Continue past the farm buildings and fences if you want to explore the closed terrain beyond the farm.",
            },
            {
                mapID = 1437,
                x = 0.2920,
                y = 0.6660,
                label = "Tunnel to Nothing",
                note = "Reach the nearby tunnel entrance shown in the exploration sources. The tunnel does not lead anywhere useful; hearthstone is the simplest exit when finished.",
            },
        },
    },
    {
        id = "windshear-crag-under-map",
        name = "Windshear Crag Under the Map",
        category = "Hidden Areas",
        continent = "kalimdor",
        difficulty = "advanced",
        mapID = 1442,
        description = "Short but risky route under the map at Windshear Crag in Stonetalon Mountains. Primary source: Boosticuff, Under the Map in Stonetalon Mountains (Out of Bounds) | Classic WoW, https://www.youtube.com/watch?v=aoOSvbIhgXk. The source video shows the location map around Stonetalon 73.3,54.0, then climbs onto the roof outside the cave, squeezes through an unfinished terrain gap, explores below the cave, and exits through the gap shown near 0:48.",
        waypoints = {
            {
                mapID = 1442,
                x = 0.7330,
                y = 0.5400,
                label = "Windshear Crag cave",
                note = "Start at the Windshear Crag cave area shown in the source video, around Stonetalon Mountains 73.3,54.0.",
            },
            {
                mapID = 1442,
                x = 0.7315,
                y = 0.5415,
                label = "Outside building",
                note = "Stand outside the small structure at the cave mouth. Face the roof and line up for the jump onto it.",
            },
            {
                mapID = 1442,
                x = 0.7305,
                y = 0.5425,
                label = "Jump to roof",
                note = "Jump onto the roof of the building outside the cave. This is the setup point for reaching the unfinished cave opening.",
            },
            {
                mapID = 1442,
                x = 0.7298,
                y = 0.5432,
                label = "Roof edge",
                note = "Move carefully along the roof toward the cave opening. Do not run too far forward; you need to squeeze into the small missing-terrain gap.",
            },
            {
                mapID = 1442,
                x = 0.7290,
                y = 0.5440,
                label = "Squeeze gap",
                note = "Squeeze into the hole where the terrain does not fully meet the cave opening. Small sidesteps and camera turns help you slip under the map.",
            },
            {
                mapID = 1442,
                x = 0.7285,
                y = 0.5450,
                label = "Under the cave",
                note = "You should now be under the map below the cave assets. Stay on the visible underside terrain and do not jump into the void.",
            },
            {
                mapID = 1442,
                x = 0.7275,
                y = 0.5460,
                label = "Floating vein view",
                note = "Look around under the cave; the source video shows a tin vein appearing to float because the cave assets are not loaded from this angle.",
            },
            {
                mapID = 1442,
                x = 0.7290,
                y = 0.5445,
                label = "Exit gap",
                note = "Exit by jumping back through the gap shown near 0:48 in the source video. If you jump into the void, expect to die and resurrect at the spirit healer.",
            },
        },
    },
    {
        id = "azshara-hidden-underwater-temple",
        name = "Azshara Hidden Underwater Temple",
        category = "Hidden Areas",
        continent = "kalimdor",
        difficulty = "intermediate",
        mapID = 1447,
        description = "Swim and dive route to the hidden interior of the underwater temple at Hetaera's Clutch in Azshara. Primary video source: TheWizardTrokair, Hidden Temple of Azshara - WoW Classic Exploration patch 1.13.4, https://www.youtube.com/watch?v=a4fj8AUZJMk. Supporting anchors: Wowhead comments identify Hetaera's Clutch around Azshara 56,45 and Temple of Arkkoran around 75,43.",
        waypoints = {
            {
                mapID = 1447,
                x = 0.7500,
                y = 0.4300,
                label = "Temple of Arkkoran",
                note = "Start near the Temple of Arkkoran coast. This is a useful eastern Azshara swim anchor before heading toward Hetaera's Clutch.",
            },
            {
                mapID = 1447,
                x = 0.7000,
                y = 0.4300,
                label = "Swim west",
                note = "Swim west across the Bay of Storms. Use water breathing, swim speed, or careful surface breaks if your character needs help staying underwater.",
            },
            {
                mapID = 1447,
                x = 0.6500,
                y = 0.4400,
                label = "Open water",
                note = "Continue west through open water. Watch for high-level sea mobs around the temple area and avoid fighting underwater if possible.",
            },
            {
                mapID = 1447,
                x = 0.6000,
                y = 0.4500,
                label = "Temple in sight",
                note = "The underwater temple structure should come into view. Aim for the upper outside of the temple, not the sea floor.",
            },
            {
                mapID = 1447,
                x = 0.5600,
                y = 0.4500,
                label = "Hetaera's Clutch",
                note = "Arrive at Hetaera's Clutch around Azshara 56,45. Circle the outside of the submerged temple and look for an opening near the upper structure.",
            },
            {
                mapID = 1447,
                x = 0.5560,
                y = 0.4470,
                label = "Dive to upper wall",
                note = "Dive along the upper wall of the temple. Stay close to the stonework so you can find the spot where the interior becomes visible.",
            },
            {
                mapID = 1447,
                x = 0.5530,
                y = 0.4440,
                label = "Interior angle",
                note = "Move forward into the visual gap shown in the video. The room can disappear from some camera angles, so adjust your camera and position slowly.",
            },
            {
                mapID = 1447,
                x = 0.5500,
                y = 0.4420,
                label = "Hidden temple room",
                note = "You should now see the purple hidden temple interior. The lower floor is visible but blocked by terrain underneath you, so explore the upper accessible area.",
            },
            {
                mapID = 1447,
                x = 0.5480,
                y = 0.4400,
                label = "Upper walkway",
                note = "Follow the upper walkway and pillars. Do not drop toward the lower floor; the video notes the terrain prevents reaching it from here.",
            },
            {
                mapID = 1447,
                x = 0.5560,
                y = 0.4470,
                label = "Exit to water",
                note = "Backtrack to the entry angle and swim out through the temple wall. Surface before your breath runs out, then hearthstone or swim back to shore.",
            },
        },
    },
}
